//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaffingAssign.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vIncidencias
    {
        public int CB_CODIGO { get; set; }
        public System.DateTime AU_FECHA { get; set; }
        public string AU_TIPO { get; set; }
        public short AU_TIPODIA { get; set; }
        public string CB_TURNO { get; set; }
        public string CB_PUESTO { get; set; }
        public string CB_NIVEL4 { get; set; }
        public string CB_NIVEL6 { get; set; }
        public short PE_YEAR { get; set; }
        public short PE_NUMERO { get; set; }
        public string CB_NOMBRES { get; set; }
        public string CB_APE_PAT { get; set; }
        public string CB_APE_MAT { get; set; }
        public string TB_ELEMENT { get; set; }
        public string PU_DESCRIP { get; set; }
    }
}
